### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by marcoshuck**
This PR improves documentation on README.md. Changes can be seen over here: https://github.com/marcoshuck/tflitego/blob/feature/improve_docs/README.md

### CODE REVIEW

**Comment by marcoshuck** [comment]
This PR address the following issue: #6

**Comment by nbortolotti** [comment]
Yes definitely , thanks @marcoshuck. For curiosity what is the difference between the highlight typed as a shell and bash?

**Review by nbortolotti — APPROVED** [review]

**Comment by marcoshuck** [comment]
Hey @nbortolotti, thanks for approving. Neither `bash` nor `shell script` styles worked, but they're supposed to highlight shell commands on code blocks. I'd like to do some research if it's possible to achieve this on github, gitlab offers support for `bash` but that doesn't seem to be the case for github. We can work on this on another PR.

**Comment by nbortolotti** [comment]
sounds good! let's merge this idea now and we can explore later more options on another PR.

**Pull request merged**
